# Use the latest version of the official Nginx image
FROM nginx:latest

# Copy the build folder from your React app to the Nginx html directory
COPY build/ /usr/share/nginx/html

# (Optional) If you have a custom Nginx configuration, uncomment and update the following line
# COPY build/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx and keep it running in the foreground
CMD ["nginx", "-g", "daemon off;"]
